### PR TITLE
Document query params

### PR DESCRIPTION
**Pull request by hassanshamim**
Use Model field info to populate Swagger's documentation.

The gist is, you add `help_text` to the Model fields in one of two ways:
1. Setting the `help_text` keyword arg when defining the model field
2. Setting the `help_text` attribute on the model field after it's been defined

Examples
 `example = models.CharField(required=True, help_text='yadda yadda')`
```
example = models.CharField(required=True)
example.help_text = 'yadda yadda'
```

I don't know all the models well enough to document all the query params for the front-end.  Any takers?

### CODE REVIEW

**Comment by jimtyhurst** [comment]
I will do a first draft of the `help_text` for the fields of the `BudgetHistory` model.

**Comment by jimtyhurst** [comment]
I noticed that the definitions do not trickle down to uses of a model in a serializer. For example, there are some summary serializers, e.g. `HistorySummaryBureauSerializer`, which only present a subset of the fields of BudgetHistory. But those endpoint definitions do not get the field `help_text`. For example, the Swagger HTML for:
```
/budget/history/
```
has the help_text for the fields of BudgetHistory, but the Swagger HTML for:
```
/budget/history/bureau/
```
does not have the field definitions, even though the objects shown in the response to `/budget/history/bureau/` are `BudgetHistory` objects, although only a subset of the fields are serialized in the response.

**Comment by hassanshamim** [comment]
Oh yeah that's because this is all django_filter magic.

The generic views we use check for any set pagination and filter classes.  If it finds them the Swagger can pick up on it and auto-populate those fields for us.

#112 added these pagination and filter classes to ocrb, codes, history, and kpm index views but none of the summary views.  I didn't understand their intent well enough to alter them but I think it should be as straightforward as adding a few more FilterSets and add them to the view, but I'll have to inspect.

**Comment by hassanshamim** [comment]
@jimtyhurst Updated the summary views to use pagination and filtering.  For now I just used the same Filters that the model index views are using.  It feels a little overly verbose with the amount of query param options we present vs the fields we actually return.  Trimming them down to only useful filters for each summary endpoint is simple enough though.

**Comment by jimtyhurst** [comment]
I ran this branch from my local workstation and browsed the documentation for the different endpoints. The Swagger documentation of query parameters looks good.

**Pull request merged**
