### PR TITLE
decompose settings by environment

### LINKED ISSUE #91: Support Multiple Environments
At the moment, our settings.py file is tightly coupled with our deployment details.  If you don't know some of these secret things, you can't run `manage.py test` or `manage.py runserver` locally.

To fix this, we we'll implement multiple settings.py files, one per required environment.  We'll update `manage.py` to default to using the development settings, unless the `DJANGO_SETTINGS_MODULE` environment variable is set.

### PR DESCRIPTION
**Pull request by hassanshamim**
Closes #91 

settings/base.py is settings that are unchanged, or sane defaults.  Other settings inherit from this one.

settings/dev.py has local development settings.  It is the default settings used unless specified.

To use the production settings file, either:
- Set an environment variable `DJANGO_SETTINGS_MODULE` to `budget_proj.settings.production`
- pass it as an argument to `manage.py`, i.e. `python manage.py runserver --settings=budget_proj.settings.production`

TODO for hassan
- [x] split requirements by env
- [x] Add django-debug-toolbar for dev environment
- [x] Move `ALLOWED_HOSTS` into base.py
- [ ] (maybe) rename production/add integration setting

### CODE REVIEW

**Comment by hassanshamim** [comment]
Don't merge yet.  Going to split requirements.txt into development and production, then implement django-debug-toolbar for local testing.

**Comment by hassanshamim** [comment]
1. Yes, that was intentional.  I think 'safe' or 'sane' defaults are the way to go.  Also I liked that it's a pretty obvious setting, so the intent becomes a bit more explicit (set default setting in base, override when necessary).

2.  Ooh, thanks for pointing this out.  I'll move those settings into the BASE.  I think the ideal solution would be to have a way to test whether it's building inside a docker container (via a flag or maybe looking for some docker-specific ENV var), but I'm fine with them being the default for now.  I'll add a comment that explains the reasoning.  Also, if ALLOWED_HOSTS is set in base do we need to also have them in the `project_config.py` ?

3. I'm fine with naming it whatever.  I'm unaware of the Integration environment - will it be like staging?  What is the purpose?  In general I prefer not to name settings after the infrastructure but rather the intent (test, dev, staging, prod, etc).  The intent here is to add more settings/env.py files as necessary - this is just getting the methodology/base down.

**Comment by hassanshamim** [comment]
@MikeTheCanuck I broke it 👿 .  Issue is I decomposed requirements.txt into multiple files similar to what I did for settings.  I see the following line in the `Dockerfile`

```
ADD requirements.txt /code/
ADD requirements/ /code/
RUN pip install -r requirements.txt
```

I kept requirements.txt and just had it point to requirements/prod.txt because I assumed it would make things easier, but the requirements folder doesn't get copied over to /code/

**Comment by MikeTheCanuck** [comment]
That's very cool, thanks for refactoring this to the more flexible requirements.txt. I'll gladly tune the Docker side if there's anything that isn't working for us. Thanks for the heads-up.

**Comment by MikeTheCanuck** [comment]
Possible bug: "ImportError: No module named 'debug toolbar'"

I ran `git checkout 91-multiple-environments`, `source budget_proj/bin/env.sh` and `budget_proj/bin/start-proj.sh -l` and the tail end of the logged output was this:

```
budget-service_1  | Running docker-entrypoint.sh...
budget-service_1  | [2017-03-30 19:14:29 +0000] [5] [INFO] Starting gunicorn 19.7.1
budget-service_1  | [2017-03-30 19:14:29 +0000] [5] [INFO] Listening at: http://0.0.0.0:8000 (5)
budget-service_1  | [2017-03-30 19:14:29 +0000] [5] [INFO] Using worker: sync
budget-service_1  | [2017-03-30 19:14:29 +0000] [8] [INFO] Booting worker with pid: 8
budget-service_1  | Internal Server Error: /
budget-service_1  | Traceback (most recent call last):
budget-service_1  |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
budget-service_1  |     response = get_response(request)
budget-service_1  |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 172, in _get_response
budget-service_1  |     resolver_match = resolver.resolve(request.path_info)
budget-service_1  |   File "/usr/local/lib/python3.5/site-packages/django/urls/resolvers.py", line 270, in resolve
budget-service_1  |     for pattern in self.url_patterns:
budget-service_1  |   File "/usr/local/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
budget-service_1  |     res = instance.__dict__[self.name] = self.func(instance)
budget-service_1  |   File "/usr/local/lib/python3.5/site-packages/django/urls/resolvers.py", line 313, in url_patterns
budget-service_1  |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
budget-service_1  |   File "/usr/local/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
budget-service_1  |     res = instance.__dict__[self.name] = self.func(instance)
budget-service_1  |   File "/usr/local/lib/python3.5/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
budget-service_1  |     return import_module(self.urlconf_name)
budget-service_1  |   File "/usr/local/lib/python3.5/importlib/__init__.py", line 126, in import_module
budget-service_1  |     return _bootstrap._gcd_import(name[level:], package, level)
budget-service_1  |   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
budget-service_1  |   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
budget-service_1  |   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
budget-service_1  |   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
budget-service_1  |   File "<frozen importlib._bootstrap_external>", line 673, in exec_module
budget-service_1  |   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
budget-service_1  |   File "/code/budget_proj/urls.py", line 32, in <module>
budget-service_1  |     import debug_toolbar
budget-service_1  | ImportError: No module named 'debug_toolbar'
```

It didn't cause the app or container to fail, but presumably this isn't the intended outcome.

Background: `start-proj.sh -l` is our way of launching the containerized app in the local developer context.  Previously it would start without error and run the proxied app for as long as I left the container running (i.e. until pressing [Ctrl]-C).

**Comment by hassanshamim** [comment]
Good find!  I was a bit sloppy but I tested that error locally and fixed it.  It only affected older setups in development but I've resolved it.

**Comment by MikeTheCanuck** [comment]
Ugh, sorry @hassanshamim - I buggered up the merge on this PR by deploying PR #94 in an emergency.  I added an extra line to `requirements.txt` to fix the problem with gunicorn timeouts that Brian & I have been trying to fix in [DevOps issue 49 here](https://github.com/hackoregon/devops-17/issues/49).  I'll come back to figure out how to fix this once I've confirmed we've got a healthy container in AWS.

**Comment by hassanshamim** [comment]
It's a pretty simple conflict just have to add the eventlet line to requirements/prod.txt.

I don't mind doing it - will wait to confirm #94 works / will stay before adjusting.

**Comment by MikeTheCanuck** [comment]
Yep, reverted #94 after dubious results at best.  Thanks for your patience.

**Pull request merged**
