### PR TITLE
Working Docker build via Travis

### PR DESCRIPTION
**Pull request by MikeTheCanuck**
The current arrangement of files in the **team-budget** repo fails to build in Travis.  This fixes that so that we have a working Docker build.

# Next Steps

- Enable the start of the Django app during Travis build to demonstrate the app is still running and configured properly
- Enable push of the working Docker container image to the Hack Oregon Docker Hub so that it can be deployed to AWS ECS and/or CloudFormation when Hack Oregon authorizes the additional spend

### CODE REVIEW

**Comment by MikeTheCanuck** [comment]
Update: this is now working again.  I `git reset --hard e86e6e9c7bd2bda753d55d99a06c7d8e6bbc5bdf` to roll back the accidental additions I ended up making after making this PR.

This should demonstrate a Docker build that completes successfully (you may ignore the `./bin/docker-push.sh` call at the end - that will be fixed shortly).

**Comment by jimtyhurst** [comment]
I pulled latest from travis-config branch. I get error:
```
$ docker up --build
...
web_1  | ImportError: No module named 'rest_framework_swagger'
web_1  | [2017-03-10 06:14:27 +0000] [12] [INFO] Worker exiting (pid: 12)
web_1  | [2017-03-10 06:14:27 +0000] [9] [INFO] Shutting down: Master
web_1  | [2017-03-10 06:14:27 +0000] [9] [INFO] Reason: Worker failed to boot.
budgetproj_web_1 exited with code 3
```

So I fixed `budget-proj/requirements.txt` to match `requirements.txt`. Then web service runs okay, but the Swagger endpoint at `localhost:8000/` is broken, only showing a Swagger link.

When I run locally:
```
$ ./manage.py runserver
```
then Swagger looks okay at `localhost:8000/`.

**Comment by MikeTheCanuck** [comment]
Well crap.  This PR originated in a fork I made off the project.  I created a feature branch named "travis-builds-docker" in my fork, did all the work, and PR'd it back to this project.

Now how the hell does anyone test it?

**Comment by MikeTheCanuck** [comment]
OK, here's an option for testing the PR I submitted from a remote fork - learn something new every day:

```
git remote add mike-travis https://github.com/MikeTheCanuck/team-budget.git
git fetch mike-travis
git checkout travis-builds-docker
```

Then try `docker-compose up --build` again.

**Comment by jimtyhurst** [comment]
I added Mike's remote, checked out `travis-builds-docker` branch. I get an error when executing build from top level directory:
```
$ docker-compose up --build
...
ERROR: for web  Cannot start service web: oci runtime error: container_linux.go:247: starting container process caused "exec: \"/code/docker-entrypoint.sh\": stat /code/docker-entrypoint.sh: no such file or directory"
ERROR: Encountered errors while bringing up the project.
```

I do not see a docker-entrypoint.sh file in the project.

**Comment by MikeTheCanuck** [comment]
Alright screw this.  Gonna delete every branch to do with Travis and Docker and start this all over again.  I am SO sick of fighting with Git.

**Comment by MikeTheCanuck** [comment]
Closing this dead-end PR in favour of PR #57.

**Pull request closed without merging**
