### PR TITLE
fixes issue #135

### PR DESCRIPTION
**Pull request by mxmoss**
Altered HistorySummaryByBureau so it calculates the service area
Instead of service_area_code (the actual code from the database)
return service_area_calc - calculated based on business logic from the
bureaus.
We don't need to return the service_area_code, so removing that.

### CODE REVIEW

**Comment by jimtyhurst** [comment]
The Travis build failed after Moss' last commit, but the error seems unrelated to the files he changed. This is the error:
```
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.5/site-packages/appdirs-1.4.3.dist-info/METADATA'
ERROR: Service 'budget-service' failed to build: The command '/bin/sh -c pip install -r prod.txt' returned a non-zero code: 2
```
Can somebody browse that [build log](https://travis-ci.org/hackoregon/team-budget/builds/226293376) to identify the root cause of this problem? Earlier in the build log, it looks like `appdirs-1.4.3.dist-info` directory was deleted, but I do not understand why.

**Comment by MikeTheCanuck** [comment]
Ugh, this is one of those spurious results (or maybe just something I've forgotten how I solved it).

I've seen this crop up before and it's only arisen rarely - at one point I thought it was a collision of dependencies - appdirs is specified in requirements.txt, but one of the other required packages imports another version of appdirs as a dependency - and I thought I'd solved for that dependency collision, and it hasn't bothered anyone for a month or two.

I'll restart the same build and see if this was transient or reproducible.

**Comment by MikeTheCanuck** [comment]
Build restart didn't help :(

I did a little digging and while I haven't had time to read every word, I read far enough in these two issues that it sounds like this is an understood problem, with a dubious-but-potentially-tactical solution:
https://github.com/ActiveState/appdirs/issues/89
https://github.com/pypa/pip/issues/4264

**Comment by Zak-Kent** [comment]
We just ran into the same issue with the Homelessness project. We were able to get travis to build by changing the version of appdirs in the requirements.txt file to 1.4.3 

Maybe that can help

**Comment by jimtyhurst** [comment]
Fixed Travis build by following @Zak-Kent 's advice to upgrade version of appdirs in `requirements/common.txt`:
```
appdirs==1.4.3
```

**Pull request merged**
