### PR TITLE
Transformed KPM data into "tidy data" format in a new file.

### PR DESCRIPTION
**Pull request by jimtyhurst**
I suggest that we use "tidy data" format (see README-tidy-data.md), where we extract the data out of the headers and represent that data explicitly in the table cells.

### CODE REVIEW

**Comment by MikeTheCanuck** [comment]
Thanks for this input on the data Jim!  We didn't want to invest a lot of time speculating what would be most productive for the API and frontend teams, so we just started with how it appeared in the Budget in Brief.

Since the RESTful endpoints can theoretically compose the data however the frontend(s) need it, I won't worry about the frontend implications for the moment.  For the API developers, can you help us understand how this format makes their job easier in wrangling the data or emitting it in RESTful responses?  [I don't know either way, so I'm hoping to gain some insight here.]

**Comment by jimtyhurst** [comment]
> Are you recommending this format for the way the API emits the data as a response, 
> or are you recommending this for the data storage format (e.g. in a PostgreSQL data layer)?

Both, but definitely as output from the web service. This format makes it easier to search and sort, because the data is in rows of the table, rather than being hidden in the column headings.

> For the API developers, can you help us understand how this format makes their job easier in wrangling the data or emitting it in RESTful responses?

* When the next year of data comes along, we just add rows to the table, rather than changing the schema to have more columns.
* Selecting for a certain year or set of years is a value to match in a where-clause, rather than listing different fields to include.
* Selecting for disjunction of values just lists distinct values ('Estimate' or 'Target'), rather than needing to know all the corresponding column names ('Estimate FY 2014-15', 'Target FY 2015-16', 'Estimate FY 2015-16', 'Target FY 2016-17'), which must be updated each year.
* It does a better job of showing the similarities across years. For example, Budget Type has values in {Actual, Estimate, Target, ...}, which can be seen as values in the column, rather than ad hoc values embedded in column headings.

**Comment by MikeTheCanuck** [comment]
I can definitely see advantages in constructing sql-like queries from the data (search and sort), so I can see the advantage of emitting data in this kind of format from an API endpoint.  We were struggling with the question of whether there was an advantage to declaring the more complex data types in a separate column, as you've recommended with the Units column.  [strong typing is one of my biases... ;)]

As to the data storage layer, I see your advantages and a couple of disadvantages, but at least to be able to tackle the Choose Your Own Adventure problem, I'd recommend we leave it up to the API developers to figure out how to compose the response data from the CSV prototype.  There's no advantage to adding the extra complication of a database in this iteration (especially for a dataset this small) - if we work out the bugs in the front end and API code now, we can parallelize the data layer discussions and commit ourselves to database when it becomes a bottleneck.

**Comment by jimtyhurst** [comment]
Committers - 
Please do *not* merge this pull request yet. Other team members are looking for better alternatives. I will just leave this pull request here for now and then I can 'Close' (delete without merging) it after the team has a chance to review any alternatives.

**Comment by jimtyhurst** [comment]
This pull request is no longer needed. A more complete set of tidy data has been committed:
  * Budget_in _Brief_KPM_data_All_Years.csv
  * Budget_in_Brief_OCRB_data_All_Years.csv

**Pull request closed without merging**
