### PR TITLE
Adding indexes to appropriate columns

### PR DESCRIPTION
**Pull request by MikeTheCanuck**
Adding column indexing.

When performance was still in the toilet I started researching a variety of performance improvement techniques, and one of the interesting results I found was this:
https://www.djangorocks.com/snippets/indexing-your-django-models.html

Now, what little database theory I've picked up over the years leaves me with the impression that you should always index the columns that are used in query parameters.  However, I've also heard it asserted that if you have too many indexes on a table, that performance will tank (but only on INSERTs).  I wasn't sure if it had some impact on READ performance, but the team assures me no.

### CODE REVIEW

**Comment by MikeTheCanuck** [comment]
Weirdly, the builds from this PR threw an exception I've never seen before:

```
Step 8 : ENTRYPOINT /code/bin/docker-entrypoint.sh
 ---> Running in 734b1db8fbff
 ---> 06f5ed683a05
Removing intermediate container 734b1db8fbff
Successfully built 06f5ed683a05
Creating network "budgetproj_default" with the default driver
Using existing test database for alias 'default'...
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: relation "budget_app_budgethistory_fiscal_year_749f4365_uniq" already exists
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/commands/test.py", line 29, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/commands/test.py", line 72, in handle
    failures = test_runner.run_tests(test_labels)
  File "/usr/local/lib/python3.5/site-packages/django/test/runner.py", line 549, in run_tests
    old_config = self.setup_databases()
  File "/usr/local/lib/python3.5/site-packages/django/test/runner.py", line 499, in setup_databases
    self.parallel, **kwargs
  File "/usr/local/lib/python3.5/site-packages/django/test/runner.py", line 743, in setup_databases
    serialize=connection.settings_dict.get("TEST", {}).get("SERIALIZE", True),
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/creation.py", line 70, in create_test_db
    run_syncdb=True,
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 130, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/operations/fields.py", line 204, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 495, in alter_field
    old_db_params, new_db_params, strict)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/postgresql/schema.py", line 117, in _alter_field
    new_db_params, strict,
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 683, in _alter_field
    self.execute(self._create_index_sql(model, [new_field], suffix="_uniq"))
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 112, in execute
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "budget_app_budgethistory_fiscal_year_749f4365_uniq" already exists
```

**Comment by mxmoss** [comment]
It's probably because the index already exists on the database, but the migration doesn't know it.
You probably ran the migration while testing, but ran it against the staged database (not your local).

Options:
- manually drop the index from the staged database & then run migrations as it's deployed
- somehow tell the build to ignore that migration
existingindex

**Comment by MikeTheCanuck** [comment]
I inspected the "Indexes" object on each of the target database tables using PgAdmin and noticed the same thing as @mxmoss - weirdly, it appears that all of the indexes were in fact built, even though psycopg2 threw an exception.  [In fact it threw an exception on one of the initial indexes I'd added in a previous commit - I'd expected that the migration would incrementally add what was missing, not barf if a specified index already existed.]

I manually deleted all indexes from the "budget" DB using PgAdmin and re-ran the last build on this branch.  Travis failed again with the same error, which is when I noticed this:

```
Using existing test database for alias 'default'...
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: relation "budget_app_budgethistory_fiscal_year_749f4365_uniq" already exists
```

It appears Travis was operating on the "test_budget" database, and there instead of *all* the indexes, all I saw was the three "fy"/"fiscal_year" indexes that were part of the first commit on this branch.

[This also implies that our recent theory on the value of running the tests in Travis may be wrong - I now believe that even with empty database tables, the test cases that validate whether the endpoints are sending valid JSON should still be a useful smoke test - an empty JSON array is still valid JSON, and if the Django code is no longer serializing the database response correctly, that should appropriately fail the test case.]

I have deleted the spurious indexes on the test_budget database and re-ran [Build 447](https://travis-ci.org/hackoregon/team-budget/builds/223014982) again.  This time around the build and tests passed and the deploy occurred.

**Comment by MikeTheCanuck** [comment]
Looks good - that deploy stabilized quickly and data is coming back, so I will infer that the indexing didn't regress anything significant.  Merging and closing.

**Pull request merged**
